### ISSUE TITLE
Helsedirektoratet tar ikke imot disse meldingene

### ISSUE THREAD

**Issue by neslekkim** [hdir/Dhhr.KppParser#1]
Hdir sier man mangler 2 nivå hodemelding?

**Comment by kryel** [comment]
Ah, ja det stemmer.
Takk for at du tok kontakt 🙂 Beklager at vi ikke så det før nå.

**Comment by neslekkim** [comment]
Jah, tenkte det er kult at dere tar ibruk Github, og håper dere får flere prosjekter over hit, transparent og slikt.
Og da var det jo også greit å melde bugs i dette systemet :) (I den grad dere ønsker det denne veien, eller om dere vil at ting skal meldes inn et annet sted. )

**Comment by kryel** [comment]
Skal være løst i [v1.2.0](https://github.com/hdir/Dhhr.KppParser/releases/tag/v1.2.0)
Merk at det er kommet nye argumenter til konsoll-appen.

**Comment by kryel** [comment]
> Jah, tenkte det er kult at dere tar ibruk Github, og håper dere får flere prosjekter over hit, transparent og slikt.
> Og da var det jo også greit å melde bugs i dette systemet :) (I den grad dere ønsker det denne veien, eller om dere vil at ting skal meldes inn et annet sted. )

Meld gjerne fra her, men vi har i skrivende stund ikke rutiner på å sjekke her, så følg gjerne opp på "gamlemåten" også
