### ISSUE TITLE
Periode, Avsenderinfo etc.

### ISSUE THREAD

**Issue by neslekkim** [hdir/Dhhr.KppParser#7]
Hadde vært kjekt om gui hadde defaulta til 1.1.<året før> og 31.12.<året før>
Hadde også vært snedig om man f.eks kunne lagret i configfila path til hvor man henter filene.
Og at man kunne lagret i samme configfil, avsender info.

Jeg hjelper et foretak med innsendinger, og bommer stadig på datoene, samt at jeg må lete etter herid'ene (foretaket selv har ikke helt oversikt over disse herid'ene)
(sånn sett så burde jo Adresseregisteret ha vært tilgjengelig utenfor nhn for oppslag, ikke bare test-versionen (https://register-web.test.nhn.no/Ar), men det er jo andres bord da.)

**Comment by gjermund-stensrud** [comment]
Hei

Takk for innspill. Det er nå lagt ut en ny versjon v1.5.1 med endringene du foreslo.
